[WIP] Feature/single asset entry #12
elasticdao/elasticswap pull request #18
Opened 2021-06-25 17:21 UTC by pelsasser

Issue: #12 

Implements single asset entry and some basic tests.  Looking to get some early feedback from @dmvt or @smalldutta (or anyone else for that matter).

Will squash all commits prior to merge.

2021-06-29 10:13 UTC, dmvt requested changes

2021-06-29 10:13 UTC, dmvt commented on src/contracts/Exchange.sol
> +        quoteTokenQty = MathLib.calculateQtyToReturnAfterFees(
This calculation will only work when the balances are equal or greater than the internal accounting. We need to check and, if needed, update the internal accounting to match the balances relative to omega prior to calculating the quoteTokenQty. Without doing so fee on transfer / negative rebase events will result in the curve being incorrect. This could result in the quote token being drained to zero.

2021-06-29 12:15 UTC, pelsasser commented on src/contracts/Exchange.sol
> +        quoteTokenQty = MathLib.calculateQtyToReturnAfterFees(
Correct. We have an open issue tracking this.  So on every trade, you are suggesting we check decay, and if the decay is in the base token, we modify our internal accounting of quoteToken and base token (based on Sigma, not omega, because we need to hold price constant).

2021-06-29 12:22 UTC, pelsasser commented on src/contracts/Exchange.sol
> +        internalBaseTokenReserveQty += baseTokenQty;
I think we should walk through the example on a call if you have time.  In your scenario, Omega is modified by the rebase, but then Omega (A/B) is staying constant.  We are using the ratio of A/B to determine the correct liquidity of each token that needs to be added.

2021-07-02 17:12 UTC, pelsasser commented on src/contracts/Exchange.sol
> +        quoteTokenQty = MathLib.calculateQtyToReturnAfterFees(
I think this has been resolved in the latest commit - 744c75b

2021-07-02 17:13 UTC, pelsasser commented on src/contracts/Exchange.sol
> +        internalBaseTokenReserveQty += baseTokenQty;
resolved by currently not allowing double asset entry when decay is present.

2021-07-02 17:42 UTC, pelsasser commented on src/contracts/Exchange.sol
> +        uint256 baseTokenQty =
@dmvt - please give this a look and a second to think about

There are 3 possible scenarios and in my view we are handling them all in the optimal way:

1) No decay, all is well
2) alpha decay (rebase up) - all is well, we are respecting the decay and not reducing the liquidity by adding the additional alpha
3) beta decay (rebase down) - we could theoretically recalculate the curve (leaving omega constant), but this would in effect take the beta decay and allow it to be used for additional liquidity which I don't think is the right outcome.

2021-07-02 18:25 UTC, dmvt approved these changes
LGTM :shipit:

2021-07-02 19:09 UTC, pelsasser commented
Adding @smalldutta  for a review prior to merging.

2021-07-05 17:11 UTC, pelsasser commented
resolved all issues raised by @smalldutta and @dmvt - merging!

2021-07-05 17:11 UTC, merged