Feature/math-documentation
elasticdao/elasticswap pull request #39
Opened 2021-07-15 15:15 UTC by smalldutta

Resolves #32 

Acceptance criteria:
- Covers all terminologies
- Explains all the features of ElasticSwap v1
- Covers rebase Up and down scenarios

2021-07-15 19:31 UTC, pelsasser requested changes
nice work @smalldutta !

I have some small comments and then an error in the math that needs to be fixed.

I will push a commit momentarily with a few small spelling errors that don't deserve discussion ;)

2021-07-15 19:31 UTC, pelsasser commented on ElasticSwapMath.md
> +The initial sheet from which the model was derived from can be found [here](https://docs.google.com/spreadsheets/d/1bAX4x2MQWlfI3c0x6QRzlxhODL0ut1dLrqabWDc98eM/edit?usp=sharing).
I wonder if we should publish this in a different format than or chicken scratch, or potentially not include it.  It is somewhat un readable to an outsider at this point.

2021-07-15 19:31 UTC, pelsasser commented on ElasticSwapMath.md
> +- `XDash (X')` -> `X' = ΔX + X` - The new value of `X` (when there is presence of `DeltaX (ΔX)`)
should we state the `new value of X after the transaction has taken place` or something similar?

2021-07-15 19:31 UTC, pelsasser commented on ElasticSwapMath.md
> +- `XDash (X')` -> `X' = ΔX + X` - The new value of `X` (when there is presence of `DeltaX (ΔX)`)
ditto for other `Dash` terms

2021-07-15 19:31 UTC, pelsasser commented on ElasticSwapMath.md
> +- `Alpha (α)` - The balance of `quoteToken` currently in the exchange.
`The ERC20 balance of ...` might be slightly more distinguishable from our internal accounting.

2021-07-15 19:31 UTC, pelsasser commented on ElasticSwapMath.md
> +- `AlphaDecay (α^)` - `α-X` - The amount of `Alpha(α)` not contributing to the liquidity.
maybe we should add why it's not contributing? Something like

`not contributing to liquidity due to an imbalance in the tokens caused by elastic supply (a rebase)` or something.

2021-07-15 19:31 UTC, pelsasser commented on ElasticSwapMath.md
> +It is the presence of `X`, `Y`, `Alpha(α)`, `Beta(β)` that allows the ElasticSwap v1 to support stable pricing on rebases for an elastic-non elastic supply token pair. This is done with the concept o
`It is the presence of `X`, `Y`, `Alpha(α)`, `Beta(β)` that allows` might read clearer 

`The presence of the terms `X`, `Y`, `Alpha(α)`, `Beta(β)` allows...`

2021-07-15 19:31 UTC, pelsasser commented on ElasticSwapMath.md
> +- When there is an increase in the supply of the `quoteToken`, essentially the value of `Alpha(α)` has increased, considering the situation where there was no decay prior to the rebase event, i.e ini
I think we should replace `value` with `quantity` to disambiguate some idea of price that could be associated with the word `value`

2021-07-15 19:31 UTC, pelsasser commented on ElasticSwapMath.md
> +Liquidity Tokens `Ro` are provided to liquidity providers.
`Liquidity Tokens , `Ro`, are provided to liquidity providers.`

2021-07-15 19:31 UTC, pelsasser commented on ElasticSwapMath.md
> +Liquidity Tokens `Ro` are provided to liquidity providers.
markdown rendered that oddly, just think we may need a comma there.

2021-07-15 19:31 UTC, pelsasser commented on ElasticSwapMath.md
> +   ```solidity
I am not sure how much the code snippet aids in understanding here.  All of the math is abstracted into the MathLib so all this shows really is the transfers and mint.  I could go either way, but potentially removing it and just leaving the link may make sense.

2021-07-15 19:31 UTC, pelsasser commented on ElasticSwapMath.md
> +Liquidity tokens increase in value due to accrual of trading fees, and can be exchanged for equivalent amounts of `quoteToken` and `baseToken`.
maybe change to `The underlying redemption value of liquidity tokens increases due to the accrual of trading fees. At any time, they can be redeemed for equivalent amounts of ...`

2021-07-15 19:31 UTC, pelsasser commented on ElasticSwapMath.md
> +```solidity
this code snipper is already stale, maybe one more reason to just link to the solidity and not have the snippets in the doc.

2021-07-15 19:31 UTC, pelsasser commented on ElasticSwapMath.md
> +    Alpha = 1000000
I think we have an error.  I will walk through it here.

Alpha is 1MM on this line.

2021-07-15 19:31 UTC, pelsasser commented on ElasticSwapMath.md
> +  Alpha = 9990128.419656029387
somehow Alpha is now 9.9M , this error carries through the rest of the math.  Somehow we are off by a factor of 10.

2021-07-15 19:31 UTC, pelsasser commented on ElasticSwapMath.md
> +  Alpha = 9990128.419656029387
the qty's at the end of the example are pretty crazy, but I think it all stems from this error.

2021-07-15 19:48 UTC, smalldutta commented on ElasticSwapMath.md
> +The initial sheet from which the model was derived from can be found [here](https://docs.google.com/spreadsheets/d/1bAX4x2MQWlfI3c0x6QRzlxhODL0ut1dLrqabWDc98eM/edit?usp=sharing).
I agree, I think since this doc discusses the breadth of it, not including it should be fine

2021-07-16 12:33 UTC, smalldutta commented on ElasticSwapMath.md
> +- `XDash (X')` -> `X' = ΔX + X` - The new value of `X` (when there is presence of `DeltaX (ΔX)`)
I agree, I think saying:
The new value of `X` post the occurrence of a trade or a liquidity event, makes sense, and have used it for `YDash` as well

2021-07-16 12:35 UTC, smalldutta commented on ElasticSwapMath.md
> +- `Alpha (α)` - The balance of `quoteToken` currently in the exchange.
I agree, have added `The ERC20 balance of ...` for `Alpha ` and `Beta`

2021-07-16 12:37 UTC, smalldutta commented on ElasticSwapMath.md
> +- `AlphaDecay (α^)` - `α-X` - The amount of `Alpha(α)` not contributing to the liquidity.
I agree, have added it to the descriptions of `AlphaDecay` and `BetaDecay`.

2021-07-16 12:39 UTC, smalldutta commented on ElasticSwapMath.md
> +It is the presence of `X`, `Y`, `Alpha(α)`, `Beta(β)` that allows the ElasticSwap v1 to support stable pricing on rebases for an elastic-non elastic supply token pair. This is done with the concept o
Agreed, will make the change as suggested.

2021-07-16 12:45 UTC, smalldutta commented on ElasticSwapMath.md
> +- When there is an increase in the supply of the `quoteToken`, essentially the value of `Alpha(α)` has increased, considering the situation where there was no decay prior to the rebase event, i.e ini
Agreed, will implement the same.

2021-07-16 12:46 UTC, smalldutta commented on ElasticSwapMath.md
> +Liquidity Tokens `Ro` are provided to liquidity providers.
Copy that.

2021-07-16 12:49 UTC, smalldutta commented on ElasticSwapMath.md
> +   ```solidity
Agreed, killing that section with fire.

2021-07-16 12:51 UTC, smalldutta commented on ElasticSwapMath.md
> +Liquidity tokens increase in value due to accrual of trading fees, and can be exchanged for equivalent amounts of `quoteToken` and `baseToken`.
Yep, that part reads much clearer with the suggested change, will add that.

2021-07-16 13:30 UTC, smalldutta commented on ElasticSwapMath.md
> +  Alpha = 9990128.419656029387
> somehow Alpha is now 9.9M , this error carries through the rest of the math. Somehow we are off by a factor of 10.

Was an error in copy-pasting, that has got propagated :( , Alpha should have been same as `X = 990128.419656029387`, but an extra `9` got added in front of the number and hence the calculations are off. Thank you for spotting it

2021-07-26 16:30 UTC, pelsasser approved these changes
LGTM - thanks for all the edits!

2021-07-26 16:46 UTC, pelsasser commented on ElasticSwapMath.md
> +  baseTokens -> final - initial = 1116251.18858083767 - 100000 = 1016251.18858083767
I think this is off by an order of magnitude as well
should be 
  baseTokens -> final - initial = 1116251.18858083767 - 1000000 = 116251.18858083767

2021-07-26 16:49 UTC, smalldutta commented on ElasticSwapMath.md
> +  baseTokens -> final - initial = 1116251.18858083767 - 100000 = 1016251.18858083767
Good catch, will address it in the following commit

2021-07-26 16:52 UTC, merged